# Generated by Django 5.2.1 on 2025-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trainingmodule_driver_vehicle_vehiclephoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='fleet_size',
            field=models.CharField(choices=[('1', '1 vehicle'), ('2-5', '2-5 vehicles'), ('6-10', '6-10 vehicles'), ('11-20', '11-20 vehicles'), ('20+', 'More than 20 vehicles')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='application_status',
            field=models.CharField(choices=[('started', 'Application Started'), ('email_verified', 'Email Verified'), ('documents_uploaded', 'Documents Uploaded'), ('background_check_pending', 'Background Check Pending'), ('training_in_progress', 'Training In Progress'), ('assessment_scheduled', 'Assessment Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='started', max_length=30),
        ),
    ]
