# Generated by Django 5.2.1 on 2025-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='background_check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
