# Generated by Django 5.2.1 on 2025-06-13 21:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_background_check_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('accessibility_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mbway', 'MB Way'), ('voucher', 'Voucher')], default='cash', max_length=20)),
                ('driver_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rider_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_comment', models.TextField(blank=True)),
                ('rider_comment', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('rider_no_show', 'Rider No Show'), ('rider_cancelled', 'Rider Cancelled'), ('driver_cancelled', 'Driver Cancelled'), ('vehicle_issue', 'Vehicle Issue'), ('weather', 'Weather Conditions'), ('other', 'Other')], max_length=20)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wheelchair_used', models.BooleanField(default=False)),
                ('assistance_provided', models.JSONField(blank=True, default=list)),
                ('equipment_used', models.JSONField(blank=True, default=list)),
                ('pickup_delay_minutes', models.IntegerField(default=0)),
                ('route_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to='app.driver')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ride', to='app.ride')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='app.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.JSONField(blank=True, null=True)),
                ('end_location', models.JSONField(blank=True, null=True)),
                ('total_rides', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('break_time_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.driver')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RideAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_zone', models.CharField(blank=True, max_length=50)),
                ('dropoff_zone', models.CharField(blank=True, max_length=50)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('day_of_week', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('is_peak_hour', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('idle_time_minutes', models.IntegerField(default=0)),
                ('fuel_efficiency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('revenue_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('revenue_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='app.driverride')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_rides', models.IntegerField(default=0)),
                ('total_hours_online', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_costs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_5_star_rides', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('on_time_arrival_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_wheelchair_rides', models.IntegerField(default=0)),
                ('accessibility_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('assistance_provided_count', models.IntegerField(default=0)),
                ('average_pickup_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('utilization_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peak_hours_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='app.driver')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['driver', 'period_type', '-period_start'], name='app_driverp_driver__854ed0_idx')],
                'unique_together': {('driver', 'period_type', 'period_start')},
            },
        ),
        migrations.AddIndex(
            model_name='driverride',
            index=models.Index(fields=['driver', '-created_at'], name='app_driverr_driver__a484f0_idx'),
        ),
        migrations.AddIndex(
            model_name='driverride',
            index=models.Index(fields=['vehicle', '-created_at'], name='app_driverr_vehicle_16eb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverride',
            index=models.Index(fields=['payment_method'], name='app_driverr_payment_3c9248_idx'),
        ),
        migrations.AddIndex(
            model_name='driverride',
            index=models.Index(fields=['completed_at'], name='app_driverr_complet_4b45dc_idx'),
        ),
        migrations.AddIndex(
            model_name='driversession',
            index=models.Index(fields=['driver', '-started_at'], name='app_drivers_driver__f92950_idx'),
        ),
        migrations.AddIndex(
            model_name='rideanalytics',
            index=models.Index(fields=['day_of_week', 'hour_of_day'], name='app_rideana_day_of__b5490a_idx'),
        ),
        migrations.AddIndex(
            model_name='rideanalytics',
            index=models.Index(fields=['pickup_zone'], name='app_rideana_pickup__e1f709_idx'),
        ),
        migrations.AddIndex(
            model_name='rideanalytics',
            index=models.Index(fields=['is_peak_hour'], name='app_rideana_is_peak_85db95_idx'),
        ),
    ]
