# Generated by Django 4.2.7

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    
    dependencies = [
        ('app', '0009_prebookedride_recurringridetemplate_ridematchoffer_and_more'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='prebookedride',
            name='wheelchair_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prebookedride',
            name='assistance_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prebookedride',
            name='booking_type',
            field=models.CharField(
                choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')],
                default='one_way',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='prebookedride',
            name='waiting_duration_minutes',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(240)
                ],
            ),
        ),
    ]