# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('app', '0010_add_accessibility_fields'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='drivercalendar',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivercalendar',
            name='total_estimated_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='drivercalendar',
            name='utilization_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='drivercalendar',
            name='break_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]