# Generated by Django 5.2.1 on 2025-08-16 23:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_calendar_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prebookedride',
            name='pre_booking_min_advance_time',
        ),
        migrations.AddConstraint(
            model_name='prebookedride',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_pickup_time__gte', datetime.datetime(2025, 8, 17, 1, 49, 40, 645635, tzinfo=datetime.timezone.utc))), name='pre_booking_min_advance_time'),
        ),
    ]
